// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: UserService.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      *String                `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExistRequest) Reset() {
	*x = CheckExistRequest{}
	mi := &file_UserService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistRequest) ProtoMessage() {}

func (x *CheckExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistRequest.ProtoReflect.Descriptor instead.
func (*CheckExistRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{0}
}

func (x *CheckExistRequest) GetTargetId() *String {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type CheckExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExistResponse) Reset() {
	*x = CheckExistResponse{}
	mi := &file_UserService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistResponse) ProtoMessage() {}

func (x *CheckExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistResponse.ProtoReflect.Descriptor instead.
func (*CheckExistResponse) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{1}
}

func (x *CheckExistResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ReadOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      *String                `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOneRequest) Reset() {
	*x = ReadOneRequest{}
	mi := &file_UserService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneRequest) ProtoMessage() {}

func (x *ReadOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneRequest.ProtoReflect.Descriptor instead.
func (*ReadOneRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOneRequest) GetTargetId() *String {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type ReadOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *ReadOneResponseBody   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOneResponse) Reset() {
	*x = ReadOneResponse{}
	mi := &file_UserService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneResponse) ProtoMessage() {}

func (x *ReadOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneResponse.ProtoReflect.Descriptor instead.
func (*ReadOneResponse) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{3}
}

func (x *ReadOneResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReadOneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReadOneResponse) GetBody() *ReadOneResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type ReadOneResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` //Serialized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOneResponseBody) Reset() {
	*x = ReadOneResponseBody{}
	mi := &file_UserService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOneResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneResponseBody) ProtoMessage() {}

func (x *ReadOneResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneResponseBody.ProtoReflect.Descriptor instead.
func (*ReadOneResponseBody) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{4}
}

func (x *ReadOneResponseBody) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ReadAllPaginatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    *Int32                 `protobuf:"bytes,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	CountPerPage  *Int32                 `protobuf:"bytes,2,opt,name=count_per_page,json=countPerPage,proto3" json:"count_per_page,omitempty"`
	FirstName     *String                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *String                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      *String                `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	PhoneNumber   *String                `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         *String                `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllPaginatedRequest) Reset() {
	*x = ReadAllPaginatedRequest{}
	mi := &file_UserService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllPaginatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPaginatedRequest) ProtoMessage() {}

func (x *ReadAllPaginatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPaginatedRequest.ProtoReflect.Descriptor instead.
func (*ReadAllPaginatedRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllPaginatedRequest) GetPageNumber() *Int32 {
	if x != nil {
		return x.PageNumber
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetCountPerPage() *Int32 {
	if x != nil {
		return x.CountPerPage
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetFirstName() *String {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetLastName() *String {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetUsername() *String {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetPhoneNumber() *String {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetEmail() *String {
	if x != nil {
		return x.Email
	}
	return nil
}

type ReadAllPaginatedResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *ReadAllPaginatedResponseBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllPaginatedResponse) Reset() {
	*x = ReadAllPaginatedResponse{}
	mi := &file_UserService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllPaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPaginatedResponse) ProtoMessage() {}

func (x *ReadAllPaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPaginatedResponse.ProtoReflect.Descriptor instead.
func (*ReadAllPaginatedResponse) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllPaginatedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReadAllPaginatedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReadAllPaginatedResponse) GetBody() *ReadAllPaginatedResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type ReadAllPaginatedResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         string                 `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"` //Serialized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllPaginatedResponseBody) Reset() {
	*x = ReadAllPaginatedResponseBody{}
	mi := &file_UserService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllPaginatedResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPaginatedResponseBody) ProtoMessage() {}

func (x *ReadAllPaginatedResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPaginatedResponseBody.ProtoReflect.Descriptor instead.
func (*ReadAllPaginatedResponseBody) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllPaginatedResponseBody) GetUsers() string {
	if x != nil {
		return x.Users
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *String                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *String                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      *String                `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      *String                `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber   *String                `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         *String                `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Description   *String                `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Roles         *String                `protobuf:"bytes,8,opt,name=roles,proto3" json:"roles,omitempty"`
	Permissions   *String                `protobuf:"bytes,9,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_UserService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRequest) GetFirstName() *String {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *CreateRequest) GetLastName() *String {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *CreateRequest) GetUsername() *String {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *CreateRequest) GetPassword() *String {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *CreateRequest) GetPhoneNumber() *String {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *CreateRequest) GetEmail() *String {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *CreateRequest) GetDescription() *String {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateRequest) GetRoles() *String {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CreateRequest) GetPermissions() *String {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *CreateResponseBody    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_UserService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{9}
}

func (x *CreateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateResponse) GetBody() *CreateResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type CreateResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponseBody) Reset() {
	*x = CreateResponseBody{}
	mi := &file_UserService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponseBody) ProtoMessage() {}

func (x *CreateResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponseBody.ProtoReflect.Descriptor instead.
func (*CreateResponseBody) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{10}
}

func (x *CreateResponseBody) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      *String                `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Username      *String                `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      *String                `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     *String                `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *String                `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   *String                `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         *String                `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Description   *String                `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Roles         *String                `protobuf:"bytes,9,opt,name=roles,proto3" json:"roles,omitempty"`
	Permissions   *String                `protobuf:"bytes,10,opt,name=permissions,proto3" json:"permissions,omitempty"`
	IsActive      bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_UserService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRequest) GetTargetId() *String {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *UpdateRequest) GetUsername() *String {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *UpdateRequest) GetPassword() *String {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *UpdateRequest) GetFirstName() *String {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *UpdateRequest) GetLastName() *String {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *UpdateRequest) GetPhoneNumber() *String {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *UpdateRequest) GetEmail() *String {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *UpdateRequest) GetDescription() *String {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateRequest) GetRoles() *String {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UpdateRequest) GetPermissions() *String {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UpdateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *UpdateResponseBody    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_UserService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateResponse) GetBody() *UpdateResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type UpdateResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponseBody) Reset() {
	*x = UpdateResponseBody{}
	mi := &file_UserService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponseBody) ProtoMessage() {}

func (x *UpdateResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponseBody.ProtoReflect.Descriptor instead.
func (*UpdateResponseBody) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResponseBody) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      *String                `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveRequest) Reset() {
	*x = ActiveRequest{}
	mi := &file_UserService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRequest) ProtoMessage() {}

func (x *ActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRequest.ProtoReflect.Descriptor instead.
func (*ActiveRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{14}
}

func (x *ActiveRequest) GetTargetId() *String {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type ActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *ActiveResponseBody    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveResponse) Reset() {
	*x = ActiveResponse{}
	mi := &file_UserService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveResponse) ProtoMessage() {}

func (x *ActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveResponse.ProtoReflect.Descriptor instead.
func (*ActiveResponse) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{15}
}

func (x *ActiveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ActiveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActiveResponse) GetBody() *ActiveResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type ActiveResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveResponseBody) Reset() {
	*x = ActiveResponseBody{}
	mi := &file_UserService_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveResponseBody) ProtoMessage() {}

func (x *ActiveResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveResponseBody.ProtoReflect.Descriptor instead.
func (*ActiveResponseBody) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{16}
}

func (x *ActiveResponseBody) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      *String                `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InActiveRequest) Reset() {
	*x = InActiveRequest{}
	mi := &file_UserService_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InActiveRequest) ProtoMessage() {}

func (x *InActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InActiveRequest.ProtoReflect.Descriptor instead.
func (*InActiveRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{17}
}

func (x *InActiveRequest) GetTargetId() *String {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type InActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *InActiveResponseBody  `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InActiveResponse) Reset() {
	*x = InActiveResponse{}
	mi := &file_UserService_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InActiveResponse) ProtoMessage() {}

func (x *InActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InActiveResponse.ProtoReflect.Descriptor instead.
func (*InActiveResponse) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{18}
}

func (x *InActiveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InActiveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InActiveResponse) GetBody() *InActiveResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type InActiveResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InActiveResponseBody) Reset() {
	*x = InActiveResponseBody{}
	mi := &file_UserService_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InActiveResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InActiveResponseBody) ProtoMessage() {}

func (x *InActiveResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InActiveResponseBody.ProtoReflect.Descriptor instead.
func (*InActiveResponseBody) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{19}
}

func (x *InActiveResponseBody) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type String struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_UserService_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{20}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Int32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32) Reset() {
	*x = Int32{}
	mi := &file_UserService_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32) ProtoMessage() {}

func (x *Int32) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32.ProtoReflect.Descriptor instead.
func (*Int32) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{21}
}

func (x *Int32) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_UserService_proto protoreflect.FileDescriptor

const file_UserService_proto_rawDesc = "" +
	"\n" +
	"\x11UserService.proto\"9\n" +
	"\x11CheckExistRequest\x12$\n" +
	"\ttarget_id\x18\x01 \x01(\v2\a.StringR\btargetId\",\n" +
	"\x12CheckExistResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"6\n" +
	"\x0eReadOneRequest\x12$\n" +
	"\ttarget_id\x18\x01 \x01(\v2\a.StringR\btargetId\"i\n" +
	"\x0fReadOneResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04body\x18\x03 \x01(\v2\x14.ReadOneResponseBodyR\x04body\")\n" +
	"\x13ReadOneResponseBody\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"\xae\x02\n" +
	"\x17ReadAllPaginatedRequest\x12'\n" +
	"\vpage_number\x18\x01 \x01(\v2\x06.Int32R\n" +
	"pageNumber\x12,\n" +
	"\x0ecount_per_page\x18\x02 \x01(\v2\x06.Int32R\fcountPerPage\x12&\n" +
	"\n" +
	"first_name\x18\x03 \x01(\v2\a.StringR\tfirstName\x12$\n" +
	"\tlast_name\x18\x04 \x01(\v2\a.StringR\blastName\x12#\n" +
	"\busername\x18\x05 \x01(\v2\a.StringR\busername\x12*\n" +
	"\fphone_number\x18\x06 \x01(\v2\a.StringR\vphoneNumber\x12\x1d\n" +
	"\x05email\x18\a \x01(\v2\a.StringR\x05email\"{\n" +
	"\x18ReadAllPaginatedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04body\x18\x03 \x01(\v2\x1d.ReadAllPaginatedResponseBodyR\x04body\"4\n" +
	"\x1cReadAllPaginatedResponseBody\x12\x14\n" +
	"\x05users\x18\x01 \x01(\tR\x05users\"\xe7\x02\n" +
	"\rCreateRequest\x12&\n" +
	"\n" +
	"first_name\x18\x01 \x01(\v2\a.StringR\tfirstName\x12$\n" +
	"\tlast_name\x18\x02 \x01(\v2\a.StringR\blastName\x12#\n" +
	"\busername\x18\x03 \x01(\v2\a.StringR\busername\x12#\n" +
	"\bpassword\x18\x04 \x01(\v2\a.StringR\bpassword\x12*\n" +
	"\fphone_number\x18\x05 \x01(\v2\a.StringR\vphoneNumber\x12\x1d\n" +
	"\x05email\x18\x06 \x01(\v2\a.StringR\x05email\x12)\n" +
	"\vdescription\x18\a \x01(\v2\a.StringR\vdescription\x12\x1d\n" +
	"\x05roles\x18\b \x01(\v2\a.StringR\x05roles\x12)\n" +
	"\vpermissions\x18\t \x01(\v2\a.StringR\vpermissions\"g\n" +
	"\x0eCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04body\x18\x03 \x01(\v2\x13.CreateResponseBodyR\x04body\"-\n" +
	"\x12CreateResponseBody\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xaa\x03\n" +
	"\rUpdateRequest\x12$\n" +
	"\ttarget_id\x18\x01 \x01(\v2\a.StringR\btargetId\x12#\n" +
	"\busername\x18\x02 \x01(\v2\a.StringR\busername\x12#\n" +
	"\bpassword\x18\x03 \x01(\v2\a.StringR\bpassword\x12&\n" +
	"\n" +
	"first_name\x18\x04 \x01(\v2\a.StringR\tfirstName\x12$\n" +
	"\tlast_name\x18\x05 \x01(\v2\a.StringR\blastName\x12*\n" +
	"\fphone_number\x18\x06 \x01(\v2\a.StringR\vphoneNumber\x12\x1d\n" +
	"\x05email\x18\a \x01(\v2\a.StringR\x05email\x12)\n" +
	"\vdescription\x18\b \x01(\v2\a.StringR\vdescription\x12\x1d\n" +
	"\x05roles\x18\t \x01(\v2\a.StringR\x05roles\x12)\n" +
	"\vpermissions\x18\n" +
	" \x01(\v2\a.StringR\vpermissions\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\"g\n" +
	"\x0eUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04body\x18\x03 \x01(\v2\x13.UpdateResponseBodyR\x04body\"-\n" +
	"\x12UpdateResponseBody\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\rActiveRequest\x12$\n" +
	"\ttarget_id\x18\x01 \x01(\v2\a.StringR\btargetId\"g\n" +
	"\x0eActiveResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04body\x18\x03 \x01(\v2\x13.ActiveResponseBodyR\x04body\"-\n" +
	"\x12ActiveResponseBody\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x0fInActiveRequest\x12$\n" +
	"\ttarget_id\x18\x01 \x01(\v2\a.StringR\btargetId\"k\n" +
	"\x10InActiveResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04body\x18\x03 \x01(\v2\x15.InActiveResponseBodyR\x04body\"/\n" +
	"\x14InActiveResponseBody\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x1e\n" +
	"\x06String\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1d\n" +
	"\x05Int32\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value2\xfb\x02\n" +
	"\vUserService\x12+\n" +
	"\x06Create\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\"\x00\x12+\n" +
	"\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\"\x00\x12+\n" +
	"\x06Active\x12\x0e.ActiveRequest\x1a\x0f.ActiveResponse\"\x00\x121\n" +
	"\bInActive\x12\x10.InActiveRequest\x1a\x11.InActiveResponse\"\x00\x127\n" +
	"\n" +
	"CheckExist\x12\x12.CheckExistRequest\x1a\x13.CheckExistResponse\"\x00\x12.\n" +
	"\aReadOne\x12\x0f.ReadOneRequest\x1a\x10.ReadOneResponse\"\x00\x12I\n" +
	"\x10ReadAllPaginated\x12\x18.ReadAllPaginatedRequest\x1a\x19.ReadAllPaginatedResponse\"\x00B\x11Z\x0fcompile/serviceb\x06proto3"

var (
	file_UserService_proto_rawDescOnce sync.Once
	file_UserService_proto_rawDescData []byte
)

func file_UserService_proto_rawDescGZIP() []byte {
	file_UserService_proto_rawDescOnce.Do(func() {
		file_UserService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UserService_proto_rawDesc), len(file_UserService_proto_rawDesc)))
	})
	return file_UserService_proto_rawDescData
}

var file_UserService_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_UserService_proto_goTypes = []any{
	(*CheckExistRequest)(nil),            // 0: CheckExistRequest
	(*CheckExistResponse)(nil),           // 1: CheckExistResponse
	(*ReadOneRequest)(nil),               // 2: ReadOneRequest
	(*ReadOneResponse)(nil),              // 3: ReadOneResponse
	(*ReadOneResponseBody)(nil),          // 4: ReadOneResponseBody
	(*ReadAllPaginatedRequest)(nil),      // 5: ReadAllPaginatedRequest
	(*ReadAllPaginatedResponse)(nil),     // 6: ReadAllPaginatedResponse
	(*ReadAllPaginatedResponseBody)(nil), // 7: ReadAllPaginatedResponseBody
	(*CreateRequest)(nil),                // 8: CreateRequest
	(*CreateResponse)(nil),               // 9: CreateResponse
	(*CreateResponseBody)(nil),           // 10: CreateResponseBody
	(*UpdateRequest)(nil),                // 11: UpdateRequest
	(*UpdateResponse)(nil),               // 12: UpdateResponse
	(*UpdateResponseBody)(nil),           // 13: UpdateResponseBody
	(*ActiveRequest)(nil),                // 14: ActiveRequest
	(*ActiveResponse)(nil),               // 15: ActiveResponse
	(*ActiveResponseBody)(nil),           // 16: ActiveResponseBody
	(*InActiveRequest)(nil),              // 17: InActiveRequest
	(*InActiveResponse)(nil),             // 18: InActiveResponse
	(*InActiveResponseBody)(nil),         // 19: InActiveResponseBody
	(*String)(nil),                       // 20: String
	(*Int32)(nil),                        // 21: Int32
}
var file_UserService_proto_depIdxs = []int32{
	20, // 0: CheckExistRequest.target_id:type_name -> String
	20, // 1: ReadOneRequest.target_id:type_name -> String
	4,  // 2: ReadOneResponse.body:type_name -> ReadOneResponseBody
	21, // 3: ReadAllPaginatedRequest.page_number:type_name -> Int32
	21, // 4: ReadAllPaginatedRequest.count_per_page:type_name -> Int32
	20, // 5: ReadAllPaginatedRequest.first_name:type_name -> String
	20, // 6: ReadAllPaginatedRequest.last_name:type_name -> String
	20, // 7: ReadAllPaginatedRequest.username:type_name -> String
	20, // 8: ReadAllPaginatedRequest.phone_number:type_name -> String
	20, // 9: ReadAllPaginatedRequest.email:type_name -> String
	7,  // 10: ReadAllPaginatedResponse.body:type_name -> ReadAllPaginatedResponseBody
	20, // 11: CreateRequest.first_name:type_name -> String
	20, // 12: CreateRequest.last_name:type_name -> String
	20, // 13: CreateRequest.username:type_name -> String
	20, // 14: CreateRequest.password:type_name -> String
	20, // 15: CreateRequest.phone_number:type_name -> String
	20, // 16: CreateRequest.email:type_name -> String
	20, // 17: CreateRequest.description:type_name -> String
	20, // 18: CreateRequest.roles:type_name -> String
	20, // 19: CreateRequest.permissions:type_name -> String
	10, // 20: CreateResponse.body:type_name -> CreateResponseBody
	20, // 21: UpdateRequest.target_id:type_name -> String
	20, // 22: UpdateRequest.username:type_name -> String
	20, // 23: UpdateRequest.password:type_name -> String
	20, // 24: UpdateRequest.first_name:type_name -> String
	20, // 25: UpdateRequest.last_name:type_name -> String
	20, // 26: UpdateRequest.phone_number:type_name -> String
	20, // 27: UpdateRequest.email:type_name -> String
	20, // 28: UpdateRequest.description:type_name -> String
	20, // 29: UpdateRequest.roles:type_name -> String
	20, // 30: UpdateRequest.permissions:type_name -> String
	13, // 31: UpdateResponse.body:type_name -> UpdateResponseBody
	20, // 32: ActiveRequest.target_id:type_name -> String
	16, // 33: ActiveResponse.body:type_name -> ActiveResponseBody
	20, // 34: InActiveRequest.target_id:type_name -> String
	19, // 35: InActiveResponse.body:type_name -> InActiveResponseBody
	8,  // 36: UserService.Create:input_type -> CreateRequest
	11, // 37: UserService.Update:input_type -> UpdateRequest
	14, // 38: UserService.Active:input_type -> ActiveRequest
	17, // 39: UserService.InActive:input_type -> InActiveRequest
	0,  // 40: UserService.CheckExist:input_type -> CheckExistRequest
	2,  // 41: UserService.ReadOne:input_type -> ReadOneRequest
	5,  // 42: UserService.ReadAllPaginated:input_type -> ReadAllPaginatedRequest
	9,  // 43: UserService.Create:output_type -> CreateResponse
	12, // 44: UserService.Update:output_type -> UpdateResponse
	15, // 45: UserService.Active:output_type -> ActiveResponse
	18, // 46: UserService.InActive:output_type -> InActiveResponse
	1,  // 47: UserService.CheckExist:output_type -> CheckExistResponse
	3,  // 48: UserService.ReadOne:output_type -> ReadOneResponse
	6,  // 49: UserService.ReadAllPaginated:output_type -> ReadAllPaginatedResponse
	43, // [43:50] is the sub-list for method output_type
	36, // [36:43] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_UserService_proto_init() }
func file_UserService_proto_init() {
	if File_UserService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UserService_proto_rawDesc), len(file_UserService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_UserService_proto_goTypes,
		DependencyIndexes: file_UserService_proto_depIdxs,
		MessageInfos:      file_UserService_proto_msgTypes,
	}.Build()
	File_UserService_proto = out.File
	file_UserService_proto_goTypes = nil
	file_UserService_proto_depIdxs = nil
}
